version: "3.8"

services:
  excalidraw:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: excalidraw
    ports:
      - "3000:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
      - VITE_APP_BACKEND_V2_GET_URL=http://backend:5000/api/v2/
      - VITE_APP_BACKEND_V2_POST_URL=http://backend:5000/api/v2/post/
      - VITE_APP_FILES_BACKEND_URL=http://backend:5000/api/files
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules

  backend:
    build:
      context: ./backend
    container_name: excalidraw-backend
    volumes:
      - backend_data:/opt/backend/data
    ports:
      - "5000:5000"
    restart: on-failure

volumes:
  notused:
  backend_data:
